### ISSUE TITLE
Sale price not updating when switching cones

### ISSUE THREAD

**Issue by L4w3s** [SPGB/Ice-Cream-Stand#2]
For some reason, the sale price doesn't update correctly when switching cones, I'll show an example now. In the following image (http://prntscr.com/5ih3f4) you will see the sale price at $47.81 while using the Baby Cone, this is the correct pricing. And then now you can see what happens when I switch to the Starter Cone (http://prntscr.com/5ih387), the price remains the same at $47.81. And then when switching to the Baby Cone again (http://prntscr.com/5ih3cs), the price reduces to $47.16. Then if I were to click on the Baby Cone once more, it'd return to the full price of $47.81. I believe the reason for this is that it updates the sale price BEFORE setting the cone value when you click on a new cone, rather than after the cone value has been changed.

**Comment by SPGB** [comment]
This should now be fixed in 1.48
